using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Models
{
    //tinfo200:[2020-03-01-jmmiddle-dykstra1] - Create course class which contains the information of the course entity. 
    //tinfo200:[2020-03-01-jmmiddle-dykstra1] - Add data annotations, effects course ID, set it to not be generated by the database.
    public class Course
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int CourseID { get; set; }
        public string Title { get; set; }
        public int Credits { get; set; }

        public ICollection<Enrollment> Enrollments { get; set; }
    }
}
